### ISSUE TITLE
use crane/oxacalica overlay/flake-parts and one flake please

### ISSUE THREAD

**Issue by dzmitry-lahoda** [itsfarseen/solana-flake#2]

**Comment by itsfarseen** [comment]
Hi @dzmitry-lahoda, could you explain why this change is needed?

**Comment by dzmitry-lahoda** [comment]
what is reason to do multiflake repo? i never seens such. usually there are other ways to stucture

**Comment by Iamnotagenius** [comment]
The change is needed because flakes do not support relative paths. When I try to build it I get:
```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'solana-1.23.1'
         whose name attribute is located at /nix/store/7x87vd43nvg8pkcmya5ivl34q5y8kp9b-source/pkgs/stdenv/generic/make-derivation.nix:270:7

       … while evaluating attribute 'installPhase' of derivation 'solana-1.23.1'

         at /nix/store/2zgys11718fdq6aim4k13xg17kpgh0yj-source/flake.nix:20:7:

           19|
           20|       installPhase = ''
             |       ^
           21|         mkdir -p $out

       error: cannot fetch input 'path:./solana-cli?lastModified=1&narHash=sha256-aNu9tapxV6F7n2NvNcTr%2BHAfOygbdeKj99Qy8Zjch%2BA%3D' because it uses a relative path
```
Check this out: https://github.com/NixOS/nix/issues/3978#issuecomment-952418478

**Comment by itsfarseen** [comment]
@Iamnotagenius @dzmitry-lahoda I don't understand what changes we need. 
Could you please elaborate?

I get that we need to reorganize the flake to avoid some path issue. 
But I used to be able to use this flake. 
Is this a regression in Nix Flakes that relative paths are not allowed?

What changes are needed w.r.t crane/oxacalica, overlay/flake-parts?

**Comment by dzmitry-lahoda** [comment]
no worries. just got used yo flake per repo.
if multi flake work ok, just never used such.

**Comment by dzmitry-lahoda** [comment]
in general,  one flake one git repo. if need split flake in one repo, use flake parts. that it.

i do  not say it will not work other way, but i doubt
